import './globals.css';
import { Rubik } from 'next/font/google';

// As we now removed static pages we should build our app layout dynamically always
export const dynamic = 'force-dynamic';

const rubik = Rubik({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        {children}
      </body>
    </html>
  )
}
